# Load all required packages for GEDI Simulator
library(XML)
library(data.table)
library(tidyverse)
library(plyr)
library(geodata)
library(lidR)
library(terra)
library(optparse)
library(jsonlite)
library(BIOMASS)
library(hdf5r)
library(rhdf5)
library(whisker)
library(remake)
